### ISSUE TITLE
Could you provide an example?

### ISSUE THREAD

**Issue by ChuckSRQ** [sorpaas/etcarbon#2]
I would like to deploy my own CarbonVote. I see the code for deployment. 

Could you make an example using your carbonvote so that I may know how to deploy mine correctly? 

Also, how do we check results? And how do you open voting at a certain time and close results at a certain time?

**Comment by sorpaas** [comment]
Hi ChuckSRQ,

You need to deploy three contracts with the same code. They are for different voting opinions "Yes", "No", "This proposal is not clear". Then simply share the addresses to allow others to vote. Parity's Contracts tab can help you to do exactly that. Let me know if you need any help on this part.

You check results by looking into logs in each block. There'll be a script to do that, given there's enough interest for this project.

You don't need to "open voting" or "close voting". The logs will tell everything. It shows if there's multiple votes from the same address -- if so, only the latest one counts. It also check the timestamp of each voting log. Only those that are within the period are considered valid. Voters' balance is "snapshotted" at the "closing block" -- the last block within this period.
